"""Render the SQLAlchemy schema as Postgres DDL for Supabase.

    python -m scripts.export_schema > supabase/schema.sql

Normally not needed: the API creates the tables itself on first start
(``Base.metadata.create_all``) when DATABASE_URL points at Supabase. The SQL file
is for reviewing the schema or creating it from the Supabase SQL editor.
"""
import json

from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateIndex, CreateTable

from app import models  # noqa: F401 -- registers the tables
from app.app_config import DEFAULTS
from app.db import Base

dialect = postgresql.dialect()
print("-- ReliefSync schema (generated by scripts/export_schema.py -- do not edit by hand)\n")
for table in Base.metadata.sorted_tables:
    print(str(CreateTable(table).compile(dialect=dialect)).strip() + ";\n")
    for index in table.indexes:
        print(str(CreateIndex(index).compile(dialect=dialect)).strip() + ";")
    print()

print("-- The FastAPI backend is the only database client (it connects as the postgres role,")
print("-- which bypasses RLS). Enabling RLS without policies keeps every table closed to the")
print("-- public anon/authenticated keys of Supabase's auto-generated REST API (NFR-14/15).")
for table in Base.metadata.sorted_tables:
    print(f"ALTER TABLE {table.name} ENABLE ROW LEVEL SECURITY;")
print()

print("-- Design parameters (context doc Section 4 + Open Items), tunable at runtime")
for key, value in DEFAULTS.items():
    literal = json.dumps(value, ensure_ascii=False).replace("'", "''")
    print(f"INSERT INTO app_config (key, value) VALUES ('{key}', '{literal}') ON CONFLICT (key) DO NOTHING;")
