-- ReliefSync schema (generated by scripts/export_schema.py -- do not edit by hand)

CREATE TABLE agencies (
	id SERIAL NOT NULL, 
	name VARCHAR(120) NOT NULL, 
	phone VARCHAR(30) NOT NULL, 
	description TEXT NOT NULL, 
	incident_types JSON NOT NULL, 
	region VARCHAR(40) NOT NULL, 
	urgency_rank INTEGER NOT NULL, 
	PRIMARY KEY (id)
);


CREATE TABLE app_config (
	key VARCHAR(80) NOT NULL, 
	value JSON NOT NULL, 
	PRIMARY KEY (key)
);


CREATE TABLE users (
	id VARCHAR(36) NOT NULL, 
	name VARCHAR(120) NOT NULL, 
	phone VARCHAR(20) NOT NULL, 
	password_hash VARCHAR(255) NOT NULL, 
	phone_verified BOOLEAN NOT NULL, 
	otp_code VARCHAR(6), 
	otp_expires_at TIMESTAMP WITHOUT TIME ZONE, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	lat FLOAT, 
	lng FLOAT, 
	location_updated_at TIMESTAMP WITHOUT TIME ZONE, 
	notify_nearby BOOLEAN NOT NULL, 
	nearby_radius_km FLOAT NOT NULL, 
	fcm_token TEXT, 
	is_simulated BOOLEAN NOT NULL, 
	PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ix_users_phone ON users (phone);

CREATE TABLE notifications (
	id SERIAL NOT NULL, 
	user_id VARCHAR(36) NOT NULL, 
	kind VARCHAR(30) NOT NULL, 
	title VARCHAR(200) NOT NULL, 
	body TEXT NOT NULL, 
	data JSON NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	read_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id)
);

CREATE INDEX ix_notifications_created_at ON notifications (created_at);
CREATE INDEX ix_notifications_user_id ON notifications (user_id);

CREATE TABLE reports (
	id VARCHAR(36) NOT NULL, 
	reporter_id VARCHAR(36) NOT NULL, 
	raw_text TEXT NOT NULL, 
	input_mode VARCHAR(10) NOT NULL, 
	received_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	lat FLOAT NOT NULL, 
	lng FLOAT NOT NULL, 
	address_text TEXT, 
	is_manual_location BOOLEAN NOT NULL, 
	contact_phone VARCHAR(20), 
	photo_urls JSON NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	incident_type VARCHAR(30) NOT NULL, 
	extraction_source VARCHAR(20), 
	extraction_ms INTEGER, 
	extraction_note TEXT, 
	confirmed_at TIMESTAMP WITHOUT TIME ZONE, 
	resolution_started_at TIMESTAMP WITHOUT TIME ZONE, 
	resolved_at TIMESTAMP WITHOUT TIME ZONE, 
	resolved_by VARCHAR(20), 
	official_status VARCHAR(20) NOT NULL, 
	official_status_updated_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(reporter_id) REFERENCES users (id)
);

CREATE INDEX ix_reports_reporter_id ON reports (reporter_id);
CREATE INDEX ix_reports_status ON reports (status);

CREATE TABLE volunteer_profiles (
	user_id VARCHAR(36) NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	available_since TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	completion_count INTEGER NOT NULL, 
	selection_count INTEGER NOT NULL, 
	disaster_experience JSON NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (user_id), 
	FOREIGN KEY(user_id) REFERENCES users (id)
);


CREATE TABLE accuracy_feedback (
	id SERIAL NOT NULL, 
	report_id VARCHAR(36) NOT NULL, 
	reporter_id VARCHAR(36) NOT NULL, 
	user_id VARCHAR(36) NOT NULL, 
	matches BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (report_id, user_id), 
	FOREIGN KEY(report_id) REFERENCES reports (id), 
	FOREIGN KEY(reporter_id) REFERENCES users (id), 
	FOREIGN KEY(user_id) REFERENCES users (id)
);

CREATE INDEX ix_accuracy_feedback_report_id ON accuracy_feedback (report_id);
CREATE INDEX ix_accuracy_feedback_reporter_id ON accuracy_feedback (reporter_id);

CREATE TABLE nearby_notices (
	id SERIAL NOT NULL, 
	report_id VARCHAR(36) NOT NULL, 
	user_id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (report_id, user_id), 
	FOREIGN KEY(report_id) REFERENCES reports (id), 
	FOREIGN KEY(user_id) REFERENCES users (id)
);

CREATE INDEX ix_nearby_notices_report_id ON nearby_notices (report_id);
CREATE INDEX ix_nearby_notices_user_id ON nearby_notices (user_id);

CREATE TABLE needs (
	id VARCHAR(36) NOT NULL, 
	report_id VARCHAR(36) NOT NULL, 
	category VARCHAR(40) NOT NULL, 
	skill VARCHAR(60) NOT NULL, 
	quota INTEGER NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	exhausted BOOLEAN NOT NULL, 
	current_batch INTEGER NOT NULL, 
	batch_sent_at TIMESTAMP WITHOUT TIME ZONE, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(report_id) REFERENCES reports (id)
);

CREATE INDEX ix_needs_report_id ON needs (report_id);

CREATE TABLE participants (
	id SERIAL NOT NULL, 
	report_id VARCHAR(36) NOT NULL, 
	user_id VARCHAR(36) NOT NULL, 
	role VARCHAR(20) NOT NULL, 
	voted_done_at TIMESTAMP WITHOUT TIME ZONE, 
	last_prompt_at TIMESTAMP WITHOUT TIME ZONE, 
	last_response_at TIMESTAMP WITHOUT TIME ZONE, 
	afk BOOLEAN NOT NULL, 
	excluded BOOLEAN NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (report_id, user_id), 
	FOREIGN KEY(report_id) REFERENCES reports (id), 
	FOREIGN KEY(user_id) REFERENCES users (id)
);

CREATE INDEX ix_participants_report_id ON participants (report_id);
CREATE INDEX ix_participants_user_id ON participants (user_id);

CREATE TABLE report_extractions (
	id SERIAL NOT NULL, 
	report_id VARCHAR(36) NOT NULL, 
	field_name VARCHAR(40) NOT NULL, 
	ai_value TEXT NOT NULL, 
	value TEXT NOT NULL, 
	evidence TEXT, 
	confidence FLOAT NOT NULL, 
	corrected BOOLEAN NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(report_id) REFERENCES reports (id)
);

CREATE INDEX ix_report_extractions_report_id ON report_extractions (report_id);

CREATE TABLE sightings (
	id SERIAL NOT NULL, 
	report_id VARCHAR(36) NOT NULL, 
	user_id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (report_id, user_id), 
	FOREIGN KEY(report_id) REFERENCES reports (id), 
	FOREIGN KEY(user_id) REFERENCES users (id)
);

CREATE INDEX ix_sightings_report_id ON sightings (report_id);

CREATE TABLE volunteer_skills (
	id SERIAL NOT NULL, 
	user_id VARCHAR(36) NOT NULL, 
	skill VARCHAR(60) NOT NULL, 
	evidence VARCHAR(20) NOT NULL, 
	verified_experience INTEGER NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (user_id, skill), 
	FOREIGN KEY(user_id) REFERENCES volunteer_profiles (user_id)
);

CREATE INDEX ix_volunteer_skills_user_id ON volunteer_skills (user_id);

CREATE TABLE assignments (
	id VARCHAR(36) NOT NULL, 
	need_id VARCHAR(36) NOT NULL, 
	report_id VARCHAR(36) NOT NULL, 
	volunteer_id VARCHAR(36) NOT NULL, 
	role VARCHAR(20) NOT NULL, 
	order_number INTEGER NOT NULL, 
	travel_status VARCHAR(20) NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	accepted_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	arrived_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (report_id, volunteer_id), 
	FOREIGN KEY(need_id) REFERENCES needs (id), 
	FOREIGN KEY(report_id) REFERENCES reports (id), 
	FOREIGN KEY(volunteer_id) REFERENCES users (id)
);

CREATE INDEX ix_assignments_report_id ON assignments (report_id);
CREATE INDEX ix_assignments_need_id ON assignments (need_id);
CREATE INDEX ix_assignments_volunteer_id ON assignments (volunteer_id);

CREATE TABLE offers (
	id VARCHAR(36) NOT NULL, 
	need_id VARCHAR(36) NOT NULL, 
	report_id VARCHAR(36) NOT NULL, 
	volunteer_id VARCHAR(36) NOT NULL, 
	rank INTEGER NOT NULL, 
	score FLOAT NOT NULL, 
	distance_km FLOAT NOT NULL, 
	batch_number INTEGER, 
	notified_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	alarm_sent_at TIMESTAMP WITHOUT TIME ZONE, 
	status VARCHAR(20) NOT NULL, 
	rejected_before BOOLEAN NOT NULL, 
	responded_at TIMESTAMP WITHOUT TIME ZONE, 
	proactive BOOLEAN NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (need_id, volunteer_id), 
	FOREIGN KEY(need_id) REFERENCES needs (id), 
	FOREIGN KEY(report_id) REFERENCES reports (id), 
	FOREIGN KEY(volunteer_id) REFERENCES users (id)
);

CREATE INDEX ix_offers_report_id ON offers (report_id);
CREATE INDEX ix_offers_status ON offers (status);
CREATE INDEX ix_offers_volunteer_id ON offers (volunteer_id);
CREATE INDEX ix_offers_need_id ON offers (need_id);

-- The FastAPI backend is the only database client (it connects as the postgres role,
-- which bypasses RLS). Enabling RLS without policies keeps every table closed to the
-- public anon/authenticated keys of Supabase's auto-generated REST API (NFR-14/15).
ALTER TABLE agencies ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE volunteer_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE accuracy_feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE nearby_notices ENABLE ROW LEVEL SECURITY;
ALTER TABLE needs ENABLE ROW LEVEL SECURITY;
ALTER TABLE participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE report_extractions ENABLE ROW LEVEL SECURITY;
ALTER TABLE sightings ENABLE ROW LEVEL SECURITY;
ALTER TABLE volunteer_skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE offers ENABLE ROW LEVEL SECURITY;

-- Design parameters (context doc Section 4 + Open Items), tunable at runtime
INSERT INTO app_config (key, value) VALUES ('max_distance_km', '5.0') ON CONFLICT (key) DO NOTHING;
INSERT INTO app_config (key, value) VALUES ('score_weights', '{"evidence": 0.3, "verified_experience": 0.1, "distance": 0.4, "completion": 0.1, "similar_disaster": 0.1}') ON CONFLICT (key) DO NOTHING;
INSERT INTO app_config (key, value) VALUES ('evidence_scores', '{"self_declared": 0.7, "certified": 1.0}') ON CONFLICT (key) DO NOTHING;
INSERT INTO app_config (key, value) VALUES ('experience_cap', '10') ON CONFLICT (key) DO NOTHING;
INSERT INTO app_config (key, value) VALUES ('near_tie_threshold', '0.02') ON CONFLICT (key) DO NOTHING;
INSERT INTO app_config (key, value) VALUES ('min_score_threshold', '0.0') ON CONFLICT (key) DO NOTHING;
INSERT INTO app_config (key, value) VALUES ('max_candidates', '50') ON CONFLICT (key) DO NOTHING;
INSERT INTO app_config (key, value) VALUES ('alarm_seconds', '30') ON CONFLICT (key) DO NOTHING;
INSERT INTO app_config (key, value) VALUES ('response_window_seconds', '300') ON CONFLICT (key) DO NOTHING;
INSERT INTO app_config (key, value) VALUES ('escalate_on_all_reject', 'true') ON CONFLICT (key) DO NOTHING;
INSERT INTO app_config (key, value) VALUES ('need_catalog', '{"pemadaman_awal": {"label": "Pemadaman Api Awal", "skill": "Pemadaman Api", "quota": 3}, "evakuasi": {"label": "Evakuasi Warga", "skill": "Evakuasi", "quota": 3}, "medis": {"label": "Pertolongan Pertama", "skill": "P3K", "quota": 2}, "logistik": {"label": "Logistik & Pengungsian", "skill": "Logistik", "quota": 2}, "akses": {"label": "Pengaturan Akses & Lalu Lintas", "skill": "Pengaturan Lalu Lintas", "quota": 2}, "psikososial": {"label": "Dukungan Psikososial", "skill": "Dukungan Psikososial", "quota": 1}}') ON CONFLICT (key) DO NOTHING;
INSERT INTO app_config (key, value) VALUES ('quorum_mode', '"proportional"') ON CONFLICT (key) DO NOTHING;
INSERT INTO app_config (key, value) VALUES ('min_confirm_sources', '2') ON CONFLICT (key) DO NOTHING;
INSERT INTO app_config (key, value) VALUES ('confirm_prompt_interval_seconds', '120') ON CONFLICT (key) DO NOTHING;
INSERT INTO app_config (key, value) VALUES ('auto_resolve_hours', '24') ON CONFLICT (key) DO NOTHING;
INSERT INTO app_config (key, value) VALUES ('trust_min_reports', '3') ON CONFLICT (key) DO NOTHING;
INSERT INTO app_config (key, value) VALUES ('trust_good_ratio', '0.7') ON CONFLICT (key) DO NOTHING;
INSERT INTO app_config (key, value) VALUES ('general_nearby_radius_km', '10.0') ON CONFLICT (key) DO NOTHING;
INSERT INTO app_config (key, value) VALUES ('sim_auto_respond', 'true') ON CONFLICT (key) DO NOTHING;
INSERT INTO app_config (key, value) VALUES ('sim_accept_probability', '0.7') ON CONFLICT (key) DO NOTHING;
INSERT INTO app_config (key, value) VALUES ('sim_speed_mps', '25.0') ON CONFLICT (key) DO NOTHING;
INSERT INTO app_config (key, value) VALUES ('sim_vote_after_arrival_seconds', '60') ON CONFLICT (key) DO NOTHING;
